config/routes.rb
PhotoJar::Application.routes.draw do
  root to: "jars#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :destroy, :index]
  resources :jars do
    resources :photos, only: [:create, :index]
    resources :jar_likes, only: [:create, :destroy, :index]
  end
  resources :tags, only: [:create, :destroy, :index, :show]
  resources :photos, only: [:create, :index]
end

app/models/jar.rb
  #A jar is a collection of upto 4 uploaded photos, owned by an individual user

class Jar < ActiveRecord::Base

  attr_accessible :title, :user_id, :photos_attributes, :tags_attributes, :tag_ids, :tags

  belongs_to :user

  has_many :taggings, inverse_of: :tag
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :tags
  
  has_many :photos, inverse_of: :jar
  accepts_nested_attributes_for :photos

  has_many :jar_likes

  validates :title, presence: true, uniqueness: {scope: :user_id}

  def as_json(options={})
    json = super
    json['photos'] = photos.as_json
    json['tags'] = tags.as_json
    json['user'] = user.as_json
    json['jarLikes'] = jar_likes.as_json

    json
  end


end

app/models/jar_like.rb
class JarLike < ActiveRecord::Base
  attr_accessible :jar_id, :user_id

  validates :jar_id, presence: true, uniqueness: {scope: :user_id}
  validates :user_id, presence: true

  belongs_to :jar
  belongs_to :user
end

app/models/jar_tag.rb
class JarTag < ActiveRecord::Base
  attr_accessible :tag, :jar_id

  belongs_to :jar

  validates :tag, :jar_id, presence: true, uniqueness: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :filepicker_url, :jar_id, :div_id, :div_class

  belongs_to :jar

  def as_json(options=nil)
    super( {:only => ["filepicker_url", "jar_id", "div_id", "div_class"]} )
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings, inverse_of: :tag
  has_many :jars, through: :taggings

  validates :name, presence: true, uniqueness: true

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :jar_id, :tag_id

  belongs_to :jar, inverse_of: :taggings
  belongs_to :tag, inverse_of: :taggings

  # validates :jar, :tag_id, presence: true
  # need to fix this^^
  # validates :jar_id, uniqueness: {scope: :tag_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :email, :password, :password_confirmation, :avatar_url
  has_secure_password

  has_many :jars
  has_many :jar_likes

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  #HARTL validation code
  validates :user_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def as_json(options={})
      super(:include => :jars)
  end


  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jar_likes_controller.rb
class JarLikesController < ApplicationController
  respond_to :json

  def create
    @jar_like = JarLike.new(jar_id: params[:jar_id].to_i, user_id: params[:user_id].to_i)
    if @jar_like.save
      render json: @jar_like
    else
      render json: @jar_like.errors, status: 422
    end
  end

  def destroy
    @jar_like = JarLike.find(params[:id])
    if @jar_like.destroy
      render json: {:success => true}
    else
      render json: @jar_like.errors, status: 422
    end
  end

  def index
    @jar_likes = JarLike.find_by_jar_id(params[:jar_id])
    render json: @jar_likes
  end
end

app/controllers/jars_controller.rb
class JarsController < ApplicationController
  respond_to :json
  respond_to :html, only: [:index]

  include SessionsHelper

  def index
    @user_jars = Jar.all(include: [:photos, :jar_likes])
    respond_to do |format|
      format.html {render :index}
      format.json {render :json => @user_jars}
    end
  end

  def create
    # Handles cases where the list of tags is empty
    @strippedParams = params[:jar]
    if @strippedParams[:tags_attributes] == nil
      @strippedParams.delete(:tags_attributes)
    end
        puts @strippedParams

    @jar = Jar.new(@strippedParams)
    if @jar.save
      render json: @jar
    else
      render json: @jar.errors, status: 422
    end
  end

  def destroy
    @jar = Jar.find(params[:id])
    if @jar.destroy
      #?
    else
      render json: @jar.errors, status: 422
    end
  end

  def update
    # Handles cases where the list of tags is empty
    @jar = Jar.find(params[:id])
    @strippedParams = params[:jar]
    if @strippedParams[:tags_attributes] == nil
      @strippedParams.delete(:tags_attributes)
    end
    puts(@strippedParams)
    # Authenticates that the current user has permission to edit this jar
    if (@jar.user == current_user && @jar.update_attributes(@strippedParams))
      render json: @jar
    else
      render json: @jar.errors, status: 422
    end
  end

  def show
    @jar = Jar.find(params[:id]).includes([:photos, :jar_likes])
    render json: @jar
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :json
  # respond_to :html, only: [:index]

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      render json: @photo
    else
      render json: @photo.errors, status: 422
    end
  end

  def index
    @photos = Jar.find(params[:jar_id]).photos
    render json: @photos
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  respond_to :json

  include SessionsHelper

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to "/#"
    else
      render 'new'
      flash[:error] = 'Invalid email/password combination'
    end
  end

  def destroy
    respond_to do |format|
      format.js { render :nothing => true }
      format.json { render json: "{}", :status => :ok}
    end
    log_out
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :json

  def index
    @tags = Tag.all
    render json: @tags
  end

  def show
    @tag = Tag.find(params[:id])
    render json: @tag
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  include SessionsHelper

  def index
    @users = User.all
    render json: @users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    user = User.find(params[:id])
    render json: user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jar_likes_helper.rb
module JarLikesHelper
end

app/helpers/jars_helper.rb
module JarsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil if cookies[:remember_token].nil?
     @user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def log_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    @user = user
  end

  def log_out
    cookies[:remember_token] = nil
    session[:user_name] = nil
  end

  def logged_in?
    not session[:user_name].nil?
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jars/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="sidebar-nav" id="sidebar">
      <ul class="nav nav-list">
        <li class="footer">
        <p>&copy; Nathan Hayflick</p>
        <p><a href="https://github.com/nhayflick"> GitHub</a>
          </p>
        </li>
      </ul>
      </div>
    </div>
    <div class="span10">
       <div class="palette-night-dark container-fluid well main-space">
  <!--   <div class='span8 offset1'> -->
      <div class='row'>
        <h1 class="big-header"> <!-- header goes here --> </h1>
        <div class="jar-content" id="content"> </div>
        <div class='span8'></div>
        <div class='row'>
          <div class='span8'><br></div>
        </div><!--/row-->
      </div><!--/row-->
  <!--   </div> --><!--/span-->
  </div><!--/container-->
    </div>
  </div>
</div><!--/row-->
</div>

<script>

 //Google Analytics Package
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40936392-2', 'herokuapp.com');
  ga('send', 'pageview');

  $(function(){

   var v = document.createElement("video");
    if (v.canPlayType("video/mp4") == '') {
      window.alert("PhotoJar doesn't support your current browser! More browser-compatibility will be added soon, but in the meantime please use Chrome or Safari.")
    };

    //jQuery plugin for correct display of posting date-time info

    jQuery("abbr.timeago").timeago();
    filepicker.setKey('AE7UBn35SviLp7DDkDDAxz');
    var $content = $("#content");
    var $navbar = $("#sidebar");
    var current_user = <%= current_user.to_json.html_safe %>;
    var current_user_jars = <%= @user_jars.to_json.html_safe %>;
    var tags = <%= Tag.all.to_json.html_safe %>;


    window.PJ.initialize(
      $content,
      $navbar,
      current_user,
      current_user_jars,
      tags
    )
  });

</script>

app/views/users/new.html.erb
<!-- <h1 class='demo-headline'>Sign up</h1>

 -->
<div class="login-screen palette-night-dark">
<div class="row-fluid">
<div class="span1"></div>
<div class="login-icon span1">
  <a href="/#">
  <img src="http://4.bp.blogspot.com/-G_0bY_5OjvI/Tk7mIUHME-I/AAAAAAAABtU/XYod3Weku1U/s1600/Mason+Jar+Printable.png" style="width:60; height:90;" alt="Log into PhotoJar" /></a><br>
  <h4 class="log-in-text">Create a <small>PhotoJar</small> account.</h4>

</div>


  <div class="span8 login-form" style="text-align: center;">
    <%= form_for(@user) do |f| %>
      <p>

      <%= f.label :user_name, "User Name" %>
      <%= f.text_field :user_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.hidden_field 'avatar_url', :value => 'https://www.filepicker.io/api/file/wJbI6M9SUqYll8UGaJwn' %>

      </p>
      <p>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    </p> <br><br> <p> Already a member? </p> <br>
         <p><%= link_to "Log in to your PhotoJar account", new_session_path %></p>
    <% end %>
  </div>
</div>
</div>